# Site settings
title: My Awesome Blog
description: "Hello World site powered by GitHub Pages"
baseurl: ""
url: "https://yogitechx.github.io/yogitechx/"
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
