# Site settings
title: My Awesome Blog
description: "Technical blog on AWS, AI & Cloud Architecture"
baseurl: ""
url: "https://yogitechx.github.io/"
theme: jekyll-theme-architect

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
